#!/bin/bash

cat <<"EOF"
export GITLAB_TOKEN="NsPPCMw-YudE2wcfeh5h"
export TEAMCITY_TOKEN="eyJ0eXAiOiAiVENWMiJ9.SWpWS1ZiVy15cjJGZ1pCVDAyaUM3ZEhFeGZZ.ZTljNjIyN2MtNzg5MC00N2RmLWE4Y2QtNzI3NmQ4YTBjMTc1"
EOF
